
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import Layout from "@/components/Layout";
import ScrollToTop from "@/components/ScrollToTop";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>
          <ThemeProvider attribute="class">
            <ScrollToTop>
              <Layout children={children} />
            </ScrollToTop>
          </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
